sudo: required
services:
  - docker

before_install:
  - docker build -t gulmohar/client -f ./client/Dockerfile.dev ./client
  #- docker build -t gulmohar/server -f ./server/Dockerfile.dev ./server

script:
  - docker run gulmohar/client npm run test -- --coverage
  #- docker run gulmohar/server npm run test -- --coverage

after_success:
  #- docker build -t gulmohar/multicontainer-client ./client
  - docker build -t gulmohar/multicontainer-client -f ./client/Dockerfile.dev ./client
  - docker build -t gulmohar/multicontainer-server ./server
  - docker build -t gulmohar/multicontainer-worker ./worker
  - docker build -t gulmohar/multicontainer-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gulmohar/multicontainer-client
  - docker push gulmohar/multicontainer-server
  - docker push gulmohar/multicontainer-worker
  - docker push gulmohar/multicontainer-nginx
